# myapp/urls.py

from django.urls import path
from . import views

urlpatterns = [

    path('', views.index, name='index'),
    path('register/', views.register, name="register"),
    path('login/register/', views.register, name="register"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('voice_assistant/', views.voice_assistant, name='voice_assistant'),
    path('news/play/ETV', views.after_ETVTelugu, name='joke'),
    path('news/play/TV9_telugu', views.after_TV9telugu, name='joke'),
    path('news/play/CNBC', views.after_CNBC, name='joke'),
    path('news/play/BBC', views.after_BBC, name='joke'),
    path('entertainment/play/baahubali', views.after_bahubali, name='joke'),
    path('news/play/TV5news', views.after_TV5news, name='joke'),
    path('news/play/sunnews', views.after_sunnews, name='joke'),
    path('news/play/TV9_hindi', views.after_TV9hindi, name='joke'),
    path('news/play/TV9_kannada', views.after_TV9kannada, name='joke'),
    path('news/play/NTV', views.after_NTV, name='joke'),
    path('entertainment/play/aravinda', views.after_aravinda, name='joke'),
    path('entertainment/play/hrithik', views.after_hrithik, name='joke'),
    path('entertainment/play/lost', views.after_lost, name='joke'),
    path('entertainment/play/venom', views.after_venom, name='joke'),
    path('entertainment/play/american', views.after_american, name='joke'),
    path('entertainment/play/nun', views.after_nun, name='joke'),
    path('entertainment/play/mysterious', views.after_myst, name='joke'),
    path('entertainment/play/siima', views.after_siima, name='joke'),
    path('entertainment/play/zindagi', views.after_zindagi, name='joke'),
    path('entertainment/play/okkadu', views.after_jawani, name='joke'),
    path('cartoon/play/bheem', views.after_bheem, name='joke'),
    path('entertainment/play/iifa', views.after_iifa, name='joke'),
    path('cartoon/play/bean', views.after_bean, name='joke'),
    path('cartoon/play/dora', views.after_dora, name='joke'),
    path('cartoon/play/doramov', views.after_doramov, name='joke'),
    path('cartoon/play/nemo', views.after_nemo, name='joke'),
    path('cartoon/play/good', views.after_good, name='joke'),
    path('cartoon/play/cou', views.after_cou, name='joke'),
    path('entertainment/play/zee', views.after_cine, name='joke'),
    path('cartoon/play/oggy', views.after_oggy, name='joke'),
    path('entertainment/play/riteish', views.after_riteish, name='joke'),
    path('entertainment/play/legend', views.after_legend, name='joke'),
    path('news/play/ABN', views.after_ABN, name='joke'),
    path('news/', views.news, name='news'),
    path('music/', views.music, name='news'),
    path('about/', views.about, name='news'),
    path('contact/', views.contact, name='news'),
    path('entertainment/', views.entertainment, name='entertainment'),
    path('cartoon/', views.cartoon, name='cartoon'),
    path('about/contact', views.contact, name='contact'),
    path('about/index1', views.index, name='contact'),
    path('contact/news', views.news, name='news'),
    path('contact/about', views.about, name='about'),
    path('news/about.html', views.about, name='about'),
    path('sports/about.html', views.about, name='about'),
    path('entertainment/about.html', views.about, name='about'),
    path('cartoon/about.html', views.about, name='about'),
    path('news/contact.html', views.about, name='about'),
    path('sports/contact.html', views.about, name='about'),
    path('entertainment/contact.html', views.about, name='about'),
    path('cartoon/contact.html', views.about, name='about'),
    path('games/play_evowars/', views.play_evowars, name='play_evowars'),
    path('games/hill/', views.hill, name='play_evowars'),
    path('games/bike/', views.bike, name='play_evowars'),
    path('games/temple/', views.temple, name='play_evowars'),
    path('games/cut/', views.cut, name='play_evowars'),
    path('games/bubble/', views.bubble, name='play_evowars'),
    path('games/twenty/', views.twenty, name='play_evowars'),
    path('games/', views.games, name='play_evowars'),
]
