# Generated by Django 5.0.3 on 2024-04-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_local_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_news',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
