# Generated by Django 5.0.3 on 2024-04-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='local_news',
            name='image',
            field=models.TextField(),
        ),
    ]
