# Generated by Django 5.0.3 on 2024-04-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_news',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
