# Generated by Django 5.0.3 on 2024-04-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_local_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='International_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='National_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('desc', models.TextField()),
            ],
        ),
    ]
