# Generated by Django 5.0.3 on 2024-04-28 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_anime_car_mov_desi_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='link',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
